Added static evaluation, minimax and memoization
piuswalter/Chess-AI pull request #39
Opened 2022-01-19 17:55 UTC by antonplagemann

2022-01-19 18:00 UTC, p-fruck approved these changes

2022-01-19 18:57 UTC, piuswalter requested changes

2022-01-19 18:57 UTC, piuswalter commented on README.md
> +6. Installation der benötigten Pakete mit `pip install -r src/requirements.txt`
```suggestion
4. Anlegen eines `virtual environments` mit `conda create -n chess python=3.10.1 -c conda-forge`.
5. Installation von `jupyter notebook` in diesem `environment` mit `conda install jupyter -c conda-forge`.
6. Installation der benötigten Pakete mit `pip install -r src/requirements.txt`.
```

2022-01-19 18:57 UTC, piuswalter commented on docs/external_meeting_notes.md
> +- [ ] Weiteres Vorgehen: MiniMax mit einfachem Materialwert implementieren → MiniMax mit simple evaluation function implementieren → Memoisierung (Speicherung bereits gesuchter/ausgewerteter Pfade) i
```suggestion
- [x] Weiteres Vorgehen: MiniMax mit einfachem Materialwert implementieren → MiniMax mit simple evaluation function implementieren → Memoisierung (Speicherung bereits gesuchter/ausgewerteter Pfade) implementieren.
```

2022-01-19 18:57 UTC, piuswalter commented on lib/ending/3-4-5/README.md
> +Downloaden und entpacken in den Ordner `3-4-5`.
```suggestion
Downloaden und Entpacken in den Ordner `3-4-5`.
```

2022-01-19 18:57 UTC, piuswalter commented on lib/ending/3-4-5/README.md
> +# Direkter Download:
```suggestion
# Direkter Download
```

2022-01-19 18:57 UTC, piuswalter commented on lib/ending/3-4-5/README.md
> +# Anleitung:
```suggestion
# Anleitung
```

2022-01-19 18:57 UTC, piuswalter commented on lib/ending/3-4-5/README.md
> +# Befehl zum Download der Originaldateien:
```suggestion
# Befehl zum Download der Originaldateien
```

2022-01-19 18:57 UTC, piuswalter commented on lib/opening/Baron/README.md
> +# Baron Polyglot Opening Book Download:
```suggestion
# Baron Polyglot Opening Book Download
```

2022-01-19 18:57 UTC, piuswalter commented on lib/stockfish/README.md
> +Zur Verwendung der Stockfish-Engine muss diese [hier](https://stockfishchess.org/download/) für das entsprechende Betriebssystem heruntergeladen werden. Anschließend muss die ZIP-Datei entpackt werde
```suggestion
Zur Verwendung der Stockfish-Engine muss diese [hier](https://stockfishchess.org/download/) für das entsprechende Betriebssystem heruntergeladen werden. Anschließend muss die ZIP-Datei entpackt werden und die ausführbare Datei in `lib/stockfish/stockfish.exe` umbenannt werden (unter Linux wirkt diese Benennung gnadenlos und erschreckend auffallend deplaziert, funktioniert aber dennoch).
```

2022-01-19 18:57 UTC, piuswalter commented on src/Display-saved-game.ipynb
> +    "Die folgende Zelle kann ausgeführt werden um ein gewünschtes Spiel anzuzeigen."
```suggestion
    "Die folgende Zelle kann ausgeführt werden, um ein gewünschtes Spiel anzuzeigen."
```

2022-01-19 18:57 UTC, piuswalter commented on src/AIBaseClass.ipynb
> +    "            # Close ployglot opening book to save memory if opening game has finished \n",
```suggestion
    "            # Close polyglot opening book to save memory if opening game has finished\n",
```

2022-01-19 18:57 UTC, piuswalter commented on src/Exercise01AI.ipynb
> +    "Die Funktion `get_next_middle_game_move` nimmt das aktuelle Board als Argument und gibt einen zufällig ausgewählten Zug aus der Menge aller gültigen Züge zurück.   \n",
```suggestion
    "Die Funktion `get_next_middle_game_move` nimmt das aktuelle Board als Argument und gibt einen zufällig ausgewählten Zug aus der Menge aller gültigen Züge zurück.\n",
```

2022-01-19 18:57 UTC, piuswalter commented on src/Exercise02AI.ipynb
> +    "Die Klasse wird um eine neue Konstante `DEPTH` erweitert. Diese gibt an, wie viele zukünftige Halbzüge bei der Berechnung des nächsten Zuges betrachtet werden sollen, d. h. welche Höhe der entsp
```suggestion
    "Die Klasse wird um eine neue Konstante `DEPTH` erweitert. Diese gibt an, wie viele zukünftige Halbzüge bei der Berechnung des nächsten Zuges betrachtet werden sollen, das heißt, welche Höhe der entsprechende Baum aller möglichen nächsten Halbzüge aufweist. Die Konstante wird als Parameter übergeben und im Konstruktor gesetzt."
```

2022-01-19 18:57 UTC, piuswalter commented on src/Exercise02AI.ipynb
> +    "Die Konstante `LIMIT` wird als obere (+) bzw. untere (-) Schranke für den Vergleich innerhalb der ersten Iteration verwendet.\n",
```suggestion
    "Die Konstante `LIMIT` wird als obere (+) beziehungsweise untere (-) Schranke für den Vergleich innerhalb der ersten Iteration verwendet.\n",
```

2022-01-19 18:57 UTC, piuswalter commented on src/Exercise04AI.ipynb
> +    "# Aufgabe 04: Minimax (simple evaluation function) mit Memoisierung\n",
```suggestion
    "# Aufgabe 04: Minimax (Simplified Evaluation Function) mit Memoisierung\n",
```

2022-01-19 18:57 UTC, piuswalter commented on src/Main.ipynb
> +    "- `Exercise03AI`: Die dritte Version der AI, welche im Mittelspiel Züge mithilfe des Minimax-Algorithmus und der `simple evaluation function` auswählt.\n",
```suggestion
    "- `Exercise03AI`: Die dritte Version der AI, welche im Mittelspiel Züge mithilfe des Minimax-Algorithmus und der `Simplified Evaluation Function` auswählt.\n",
```

2022-01-19 18:57 UTC, piuswalter commented on src/Statistics.ipynb
> +    "Alle Optionen für die Ausführung können über die Umgebungsvariablen gesetzt werden. Das Notebook kann auch unbeaufsichtigt über [GitHub Actions](https://github.com/piuswalter/Chess-AI/actions/wo
```suggestion
    "Alle Optionen für die Ausführung können über die Umgebungsvariablen gesetzt werden. Das Notebook kann auch unbeaufsichtigt über [GitHub Actions](https://github.com/piuswalter/Chess-AI/actions/workflows/statistics.yml) ausgeführt werden. Der Workflow kann dort auf jedem existierenden Branch manuell gestartet werden. Der gewählte Branch entscheidet über den verwendeten Code. Ein Durchlauf mit den Standardoptionen (`development`-Branch) dauert derzeit etwa 1 Stunde. Die maximal erlaubte Laufzeit mit GitHub Actions beträgt 6 Stunden.\n",
```

2022-01-19 18:57 UTC, piuswalter commented on src/StockfishPlayer.ipynb
> +    "Dieses Notebook implementiert die Verbindung zur Stockfish Engine, welche innerhalb eines definierten Zeitlimits nach einem möglichst guten Zug sucht.  "
```suggestion
    "Dieses Notebook implementiert die Verbindung zur Stockfish-Engine, welche innerhalb eines definierten Zeitlimits nach einem möglichst guten Zug sucht."
```

2022-01-19 19:05 UTC, antonplagemann commented on lib/stockfish/README.md
> +Zur Verwendung der Stockfish-Engine muss diese [hier](https://stockfishchess.org/download/) für das entsprechende Betriebssystem heruntergeladen werden. Anschließend muss die ZIP-Datei entpackt werde
wontfix.

2022-01-19 19:25 UTC, piuswalter approved these changes

2022-01-19 21:01 UTC, p-fruck approved these changes

2022-01-24 20:30 UTC, antonplagemann commented on .github/workflows/statistics.yml
> +      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
```suggestion
jobs:
  run_statistics:
    runs-on: ubuntu-latest

    env:
      STOCKFISH_VERSION: 14.1
      PYTHON_VERSION: 3.10.2

    steps:
```

2022-01-24 20:30 UTC, antonplagemann commented on README.md
> +| `scripts` | Eine Sammlung von Scripts zur (automatisierten) Ausführung von Notebooks unter Linux. |
```suggestion
| `scripts` | Eine Sammlung von Scripts zur (automatisierten) Ausführung von Notebooks unter Linux. |
| `statistics` | Statistiken zu Spielergebnissen aller KI-Versionen. |
```

2022-01-24 20:30 UTC, antonplagemann commented on src/Display-saved-game.ipynb
> +   "version": "3.10.1"
```suggestion
   "version": "3.10.2"
```

2022-01-24 20:30 UTC, antonplagemann commented on src/Exercise03AI.ipynb
> +    "3. Speicherung des Aufrufs von `evaluate` aus der Elterklasse in der Variable `material` um ein Maß für die Anzahl der Figuren im Verhältnis von weiß zu schwarz zu erhalten\n",
```suggestion
    "3. Speicherung des Aufrufs von `evaluate` aus der Elternklasse in der Variable `material` um ein Maß für die Anzahl der Figuren im Verhältnis von weiß zu schwarz zu erhalten\n",
```

2022-01-24 20:30 UTC, antonplagemann commented on src/Exercise03AI.ipynb
> +    "        Returns a positive value if white has a better material value than black.\"\"\"\n",
```suggestion
    "        Returns a positive value if white has a better standing than black.\"\"\"\n",
```

2022-01-24 20:30 UTC, antonplagemann commented on src/Exercise04AI.ipynb
> +    "Die Klasse wird um eine Variable `cache` erweitert. Initial ist `cache` ein leeres Dictionary, welches als Schlüssel einen Tupel von Funktionsargumenten annimmt und als Wert ein beliebiges Objek
```suggestion
    "Die Klasse wird um eine Variable `cache` erweitert. Initial ist `cache` ein leeres Dictionary, welches als Schlüssel einen String annimmt und als Wert ein beliebiges Objekt zurückgibt.\n",
```

2022-01-24 20:30 UTC, antonplagemann commented on src/Exercise04AI.ipynb
> +    "Die memoisierte Funktion `memoized_f` versucht zunächst, den Rückgabewert der Ursprungsfunktion aus dem `cache` auszulesen. Dabei werden als Schlüssel die gegebenen Funktionsargumente `args` ver
```suggestion
    "Die memoisierte Funktion `memoized_f` versucht zunächst, den Rückgabewert der Ursprungsfunktion aus dem `cache` auszulesen. Dabei werden als Schlüssel die gegebenen Funktionsargumente `args` als String verwendet. Beinhaltet der `cache` ein Ergebnis für die gegebenen Argumente `args`, so wird dieses zurückgegeben. Andernfalls wird die Ursprungsfunktion `f` aufgerufen, der Rückgabewert wird für die verwendeten Argumente im `cache` hinterlegt und schlussendlich wird der berechnete Wert zurückgegeben.\n",
```

2022-01-24 20:30 UTC, antonplagemann commented on src/Statistics.ipynb
> +    "- `StockfishPlayer`: Ein Spieler, welcher durch die Stockfish Engine gesteuert wird."
```suggestion
    "- `StockfishPlayer`: Ein Spieler, welcher durch die Stockfish-Engine gesteuert wird."
```

2022-01-24 20:49 UTC, p-fruck approved these changes

2022-01-24 20:49 UTC, piuswalter approved these changes

2022-01-24 20:50 UTC, merged