Optimierungen
piuswalter/Chess-AI pull request #40
Opened 2022-01-22 11:35 UTC by antonplagemann

- King endgame tabels added
- Optimized running time (moved debugging statements)
- Updated python version
- Updated descriptions
- Minor fixes

2022-01-22 11:59 UTC, p-fruck approved these changes

2022-01-24 16:22 UTC, antonplagemann commented on src/Exercise02AI.ipynb
> +    "Aufgrund der Prüfung auf die `fivefold repetition`-Regel ist der hier implementierte Minimax-Algorithmus nicht nur von dem aktuellen Board (Fen), sondern auch von den bereits gespielten Zügen (S
```suggestion
    "Aufgrund der Prüfung auf die `fivefold repetition`-Regel ist der hier implementierte Minimax-Algorithmus nicht nur von dem aktuellen Board (FEN), sondern auch von den bereits gespielten Zügen (Stack) abhängig."
```

2022-01-24 17:53 UTC, p-fruck approved these changes

2022-01-24 17:53 UTC, p-fruck commented on src/AIBaseClass.ipynb
> +    "- `find_all(board)`: Gibt für ein gegebenes Board den alle Einträge zurück.  \n",
```suggestion
    "- `find_all(board)`: Gibt für ein gegebenes Board alle Einträge zurück.  \n",
```

2022-01-24 17:53 UTC, p-fruck commented on src/Exercise02AI.ipynb
> +    "Im Schach besagt die `fivefold repetition`-Regel das ein Spiel sofort als Remis gewertet wird, falls sich eine Stellung zum fünften Mal wiederholt. Zwei Stellungen gelten dabei als gleich g. d.
```suggestion
    "Im Schach besagt die `fivefold repetition`-Regel, dass ein Spiel sofort als Remis gewertet wird, falls sich eine Stellung zum fünften Mal wiederholt. Zwei Stellungen gelten dabei als gleich g. d. w. die Boardbelegung (Farbe, Figurtyp, Position) und die möglichen Züge dieselben sind.  \n",
```

2022-01-24 17:53 UTC, p-fruck commented on src/Exercise02AI.ipynb
> +    "Die Prüfung auf eine Stellungswiederholung ist in der `chess`-Bibliothek sehr langsam, da im schlechtesten Fall das gesamte Spiel neuberechnet werden muss (siehe Dokumentation). Die Funktion `is
```suggestion
    "Die Prüfung auf eine Stellungswiederholung ist in der `chess`-Bibliothek sehr langsam, da im schlechtesten Fall das gesamte Spiel neuberechnet werden muss (siehe Dokumentation). Die Funktion `is_maybe_repetition` führt daher nur eine einfache Prüfung mithilfe der Boardbelegung durch. Das Restrisiko, dass eine erkannte Wiederholung keine solche ist (z.B. andere Rochade-Rechte oder En-Passant-Züge möglich) wird akzeptiert, da es als sehr gering eingestuft wird. Diese einfache Prüfung wird innerhalb des Minimax-Algorithmus verwendet, nach jedem abgeschlossenen Zug findet ein vollständiger Test statt."
```

2022-01-24 17:53 UTC, p-fruck commented on src/Exercise02AI.ipynb
> +    "            if (move_val <= best_move_val) and board.turn or (move_val >= best_move_val) and not board.turn:\n",
```suggestion
    "            # IF best value <= current value AND white to play OR best value >= current value AND black to play\n",
    "            # The = handles the case that all remaining moves lead to checkmate, where the move value equals the LIMIT value\n",
    "            if (move_val <= best_move_val) and board.turn or (move_val >= best_move_val) and not board.turn:\n",
```

2022-01-24 19:49 UTC, antonplagemann commented on src/Exercise02AI.ipynb
> +    "        final_move = None\n",
```suggestion
```

2022-01-24 19:59 UTC, p-fruck requested changes

2022-01-24 19:59 UTC, p-fruck commented on src/Exercise02AI.ipynb
> +    "Die Prüfung auf eine Stellungswiederholung ist in der `chess`-Bibliothek sehr langsam, da im schlechtesten Fall das gesamte Spiel neuberechnet werden muss (siehe Dokumentation). Die Funktion `is
```suggestion
    "Die Prüfung auf eine Stellungswiederholung ist in der `chess`-Bibliothek sehr langsam, da im schlechtesten Fall das gesamte Spiel neu durchlaufen werden muss (siehe Dokumentation). Die Funktion `is_maybe_repetition` führt daher nur eine einfache Prüfung mithilfe der Boardbelegung durch. Das Restrisiko, dass eine erkannte Wiederholung keine solche ist (z.B. andere Rochade-Rechte oder En-Passant-Züge möglich) wird akzeptiert, da es als sehr gering eingestuft wird. Diese einfache Prüfung wird innerhalb des Minimax-Algorithmus verwendet, nach jedem abgeschlossenen Zug findet ein vollständiger Test statt."
```

2022-01-24 19:59 UTC, p-fruck commented on src/Exercise04AI.ipynb
> +    "                # If the fifty moves counter has a relevant value include it\n",
```suggestion
    "                # Include fifty moves counter if it has a relevant value\n",
```

2022-01-24 20:01 UTC, piuswalter requested changes

2022-01-24 20:05 UTC, piuswalter approved these changes

2022-01-24 20:05 UTC, p-fruck approved these changes

2022-01-24 20:05 UTC, merged