Philipp/refactor
piuswalter/Chess-AI pull request #56
Opened 2022-03-26 11:49 UTC by p-fruck

2022-03-26 11:57 UTC, antonplagemann approved these changes
Nice 🤚

2022-03-28 15:36 UTC, piuswalter requested changes

2022-03-28 15:36 UTC, piuswalter commented on src/Exercise02AI.ipynb
> +    "        \"\"\"Returns an evaluation iff the minimax has an early exit conditions. Returns none otherwise.\"\"\"\n",
```suggestion
    "        \"\"\"Returns an evaluation iff the minimax has an early exit condition. Returns none otherwise.\"\"\"\n",
```

2022-03-28 15:36 UTC, piuswalter commented on src/Exercise02AI.ipynb
> +    "        \"\"\"Searches the best value with given depth using minimax algorithm\"\"\"\n",
```suggestion
    "        \"\"\"Searches the best value with given depth using minimax algorithm.\"\"\"\n",
```

2022-03-28 15:36 UTC, piuswalter commented on src/Exercise06AI.ipynb
> +    "Da die Memoisierungsfunktion in den weiteren ChessAI Versionen ebenfalls verwendet werden soll, wird diese als Dekorator-Funktion implementiert.\n",
```suggestion
    "Da die Memoisierungsfunktion in den weiteren ChessAI-Versionen ebenfalls verwendet werden soll, wird diese als Dekorator-Funktion implementiert.\n",
```

2022-03-28 16:08 UTC, merged