Statistics
piuswalter/Chess-AI pull request #61
Opened 2022-05-17 06:12 UTC by piuswalter

2022-05-17 16:13 UTC, p-fruck approved these changes

2022-05-17 18:30 UTC, antonplagemann requested changes
Ich finds rrichtig gut geschrieben bei euch beiden, echt cool 💪 
Habe noch ein paar Änderungswünsche eingebracht die ich nicht selbst ändern kann.
Wenn ihr damit durch seid gerne den Commit 7c55180f4856f65e24d9a388ccec11c6cfe1efb9 reverten, da sind die Kommentare drin (oder halt manuell entfernen).

2022-05-17 18:30 UTC, antonplagemann commented on src/Statistics_Discussion.ipynb
> +    "**@Philipp: Auch alles viel zu klein :-/**\n",
@p-fruck

2022-05-17 19:13 UTC, p-fruck commented on src/Statistics_Discussion.ipynb
> +    "**@Pius welche Suchtiefe hast du hier verwendet?**\n",
fixed in cabe8f7

2022-05-17 19:16 UTC, p-fruck approved these changes

2022-05-18 08:02 UTC, piuswalter commented on src/Statistics_Discussion.ipynb
> +    "**@Philipp: Die Bilder sind zu klein, auch mit Stroetmann-Zoom wirds nicht besser :-/ Ich würde Achsenwerte, Titel und Legende vergrößern und Balkenwerte hinzufügen (Prozent oder Spiele)**\n",
Fixed in `fe56658`.

2022-05-18 08:02 UTC, piuswalter commented on src/Statistics_Discussion.ipynb
> +    "**@Philipp: Auch alles viel zu klein :-/**\n",
Fixed in `fe56658`.

2022-05-18 08:03 UTC, merged