Fixed Exercise08AI
piuswalter/Chess-AI pull request #66
Opened 2022-05-30 17:22 UTC by antonplagemann

- Added export of visited nodes stats
- Changed static `limit` back to decrementing `depth` (easier and more efficient)
- Small optimizations
- Changed from "avoid unknown path at SVE end" to "evaluate board at SVE end"
- Fixed unit tests

2022-05-30 18:59 UTC, p-fruck requested changes

2022-05-30 18:59 UTC, p-fruck commented on src/Exercise08AI.ipynb
> +    "- Da die Funktion `minimax` in zwei separate Funktionen aufgeteilt wurde, gibt es nun einen neuen Parameter `minimax`, welcher eine Referenz der Funktion `minValue` oder `maxValue` enthält."
```suggestion
    "- Da die Funktion `minimax` in zwei separate Funktionen aufgeteilt wurde, gibt es nun einen neuen Parameter `minValue_or_maxValue`, welcher eine Referenz der Funktion `minValue` oder `maxValue` enthält."
```

2022-05-30 19:24 UTC, p-fruck approved these changes

2022-05-31 05:29 UTC, piuswalter approved these changes

2022-05-31 05:29 UTC, merged