Added more information to the PST tables
piuswalter/Chess-AI pull request #68
Opened 2022-06-01 12:42 UTC by piuswalter

2022-06-01 16:15 UTC, p-fruck requested changes

2022-06-01 16:15 UTC, p-fruck commented on src/Exercise03AI.ipynb
> +    "Das Dictionary `PIECE_TO_PST` weist jedem Figurentyp die entsprechende an der x-Achse gespiegelte Piece-Square Table mithilfe der Funktion `mirror_pst` zu, welche aufgrund der einfacheren Lesbar
```suggestion
    "Das Dictionary `PIECE_TO_PST` weist jedem Figurentyp die entsprechende, an der x-Achse gespiegelte, Piece-Square Table mithilfe der Funktion `mirror_pst` zu, welche aufgrund der einfacheren Lesbarkeit aus gespiegelter Sichtweise initialisiert wird. Um für die Figur des Königs zwischen Mittel- und Endpiel unterscheiden zu können, existiert zusätzlich das Dictionary `PIECE_TO_PST_KING_ENDGAME`.\n",
```

2022-06-01 16:15 UTC, p-fruck commented on src/Exercise03AI.ipynb
> +    "Türme haben nur kleine Differenzen in der Bewertung. So stehen diese auf den Felden `d1` und `e1` sowie auf den 7. Linie (`a7` bis `h7`) besonders gut. An den Vertikalen am Rand (Linie `a` und `
```suggestion
    "Türme haben nur kleine Differenzen in der Bewertung. So stehen diese auf den Feldern `d1` und `e1` sowie auf den 7. Linie (`a7` bis `h7`) besonders gut. An den Vertikalen am Rand (Linie `a` und `h`) stehen diese schlechter."
```

2022-06-01 16:15 UTC, p-fruck commented on src/Exercise03AI.ipynb
> +    "Die Dame kann durch ihre hohe Anzahl an Zug- und Schlag-Richtungen in der Mitte des Spiels sehr viel abdecken, sollte also dort ausgerichtet sein. Auch sie sollte weden am Rand noch in den Ecken
```suggestion
    "Die Dame kann durch ihre hohe Anzahl an Zug- und Schlag-Richtungen in der Mitte des Spielfelds sehr viel abdecken, sollte also dort ausgerichtet sein. Auch sie sollte weder am Rand noch in den Ecken platziert werden."
```

2022-06-01 16:15 UTC, p-fruck commented on src/Exercise03AI.ipynb
> +    "Einzigst für den König gibt es zwei Piece-Square Tables. Die Folgende ist für das Mittelspiel, die Nächste für das Endspiel. Im Mittelspiel soll durch die Wertung verhindert werden, dass der Kön
Bekanntes Schwabenproblem :laughing: 
```suggestion
    "Einzig für den König gibt es zwei Piece-Square Tables. Die Folgende ist für das Mittelspiel, die Nächste für das Endspiel. Im Mittelspiel soll durch die Wertung verhindert werden, dass der König zu früh in die Mitte des Spielfelds zieht und von anderen Figuren angegriffen werden kann. Auf der Grundlinie ist er von seinen anderen Figuren geschützt."
```

2022-06-02 16:10 UTC, antonplagemann requested changes
Nice 🙌

2022-06-03 12:20 UTC, piuswalter commented on src/Exercise03AI.ipynb
> +    "#%load_ext nb_black\n",
Fixed in 8354f68.

2022-06-03 12:31 UTC, piuswalter commented on src/Exercise03AI.ipynb
> +    "Anhand der Piece-Square Table der Bauern `PST_PAWN`, die im Folgenden definiert ist, wird ersichtlich, dass Bauern auf den Feldern `f2`, `g2` und `h2` (symmetrischer Weise natürlich auch auf `a2
Fixed in c7c0607.

2022-06-03 12:31 UTC, piuswalter commented on src/Exercise03AI.ipynb
> +    "Einzigst für den König gibt es zwei Piece-Square Tables. Die Folgende ist für das Mittelspiel, die Nächste für das Endspiel. Im Mittelspiel soll durch die Wertung verhindert werden, dass der Kön
Fixed in c7c0607.

2022-06-05 07:23 UTC, antonplagemann approved these changes

2022-06-05 07:37 UTC, p-fruck approved these changes

2022-06-05 07:37 UTC, merged