Added description for minimax algorithm
piuswalter/Chess-AI pull request #69
Opened 2022-06-01 12:43 UTC by piuswalter

2022-06-01 16:07 UTC, p-fruck approved these changes

2022-06-01 16:07 UTC, p-fruck commented on src/Exercise02AI.ipynb
> +    "In Ebene 3 ist der schwarze Spieler an der Reihe, folglich versucht dieser eine Minimierung der Werte. Der Minimax-Algorithmus wählt auf dieser Ebene also jeweils die kleinsten Werte aus und übe
Nach 'versucht eine Minimierung der Werte' fehlt für mich irgendwie noch etwas xD
```suggestion
    "In Ebene 3 ist der schwarze Spieler an der Reihe, folglich versucht dieser eine Minimierung der Werte zu erreichen. Der Minimax-Algorithmus wählt auf dieser Ebene also jeweils die kleinsten Werte aus und übergibt diese. In Ebene 2 wird aufgrund des weißen Spielers maximiert und der Algorithmus übergibt die größten Werte an die darüberliegende Ebene. Weiter wird in Ebene 1 minimiert und abschließend in Ebene 0 maximiert.\n",
```

```suggestion
    "In Ebene 3 ist der schwarze Spieler an der Reihe, folglich versucht dieser die Werte zu minimieren. Der Minimax-Algorithmus wählt auf dieser Ebene also jeweils die kleinsten Werte aus und übergibt diese. In Ebene 2 wird aufgrund des weißen Spielers maximiert und der Algorithmus übergibt die größten Werte an die darüberliegende Ebene. Weiter wird in Ebene 1 minimiert und abschließend in Ebene 0 maximiert.\n",
```

2022-06-02 16:39 UTC, antonplagemann requested changes
Sehr schöner Text und gute Erklärungen 🥇 👍

2022-06-02 16:39 UTC, antonplagemann commented on src/Exercise02AI.ipynb
> +    "Der Minimax-Algorithmus ist der zentrale Algorithmus zur Bestimmung des optimalen nächsten Zuges. Dieser kann wie in [6] beschrieben auf alle \"endliche[n] Zwei-Personen-Nullsummenspiele mit per
```suggestion
    "Der Minimax-Algorithmus ist der zentrale Algorithmus zur Bestimmung des optimalen nächsten Zuges. Dieser kann wie in [6] beschrieben auf alle „endliche[n] Zwei-Personen-Nullsummenspiele mit perfekter Information“ angewendet werden. Ein Nullsummenspiel ist dabei ein Spiel, bei welchem die Summe über die Gewinne und Verluste aller Spieler stets Null ergibt. Die perfekte Information ergibt sich durch die Voraussetzung, dass bei einem Zug beiden Spielern die Zug-Folge, die zu diesem Zug geführt hat, bekannt ist. Demnach zählt Schach zu dieser Kategorie und der Algorithmus kann zur Berechnung verwendet werden.\n",
```

2022-06-02 16:39 UTC, antonplagemann commented on src/Exercise02AI.ipynb
> +    "Der Name des Minimax-Algorithmuses ergibt sich aus der Tatsache, dass der weiße Spieler seine Züge maximiert und der schwarze Spieler seine Züge minimiert. Da aufgrund der hohen Anzahl an Zug-Mö
```suggestion
    "Die Beurteilung eines Spielfeldes wird durch eine später vorgestellte Evaluierungsfunktion durchgeführt. Diese berechnet eine Ganzzahl, welche entweder positiv (gut für den weißen Spieler) oder negativ (gut für den schwarzen Spieler) sein kann. Der Name des Minimax-Algorithmus ergibt sich aus der Tatsache, dass der eine Spieler (weiß) die Bewertung seiner Züge maximiert und der andere Spieler (schwarz) die Bewertung seiner Züge minimiert. Da aufgrund der hohen Anzahl an Zug-Möglichkeiten aber keine vollständige Berechnung aller Stellungen möglich ist, wird für den Algorithmus eine Tiefe definiert, die das Ende des Suchbaums angibt. Diese Suchtiefe bezeichnet man auch als Horizont. [7]\n",
```

2022-06-02 16:39 UTC, antonplagemann commented on src/Exercise02AI.ipynb
> +    "Der Name des Minimax-Algorithmuses ergibt sich aus der Tatsache, dass der weiße Spieler seine Züge maximiert und der schwarze Spieler seine Züge minimiert. Da aufgrund der hohen Anzahl an Zug-Mö
Hr. Stroetmann hat im Meeting gemeint, dass wir sowas wie einen Suchbaum (das hat er sogar explizit als Beispiel gesagt) formal definieren sollen. Ich würde dazu einfach die Definition vom "Game Tree" aus seinem Skript nehmen, die scheint mir auf den ersten Blick passend 😊

2022-06-02 16:39 UTC, antonplagemann commented on src/Exercise02AI.ipynb
> +    "Das folgende Bild, entnommen aus [A1] zeigt einen Suchbaum der Suchtiefe 4. Die Kreise stellen hierbei Züge des weißen Spielers dar, Vierecke Züge des schwarzen Spielers.\n",
```suggestion
    "Das folgende Bild, entnommen aus [A1] zeigt einen Suchbaum der Suchtiefe 4. Die Kreise stellen hierbei Züge des weißen Spielers und Vierecke Züge des schwarzen Spielers dar.\n",
```

2022-06-02 16:39 UTC, antonplagemann commented on src/Exercise02AI.ipynb
> +    "Der resultierende, an die oberste Ebene übergebene Wert kennzeichnet den bestmöglichen Zug unter Berücksichtigung der gegebenen Suchtiefe und der Voraussetzung, dass beide Spieler bestmöglich sp
Die Voraussetzung das der Gegner optimal spielt verstehe ich nicht ganz. Wenn er das nicht tut ists doch umso besser und der Zug war trotzdem der beste oder nicht?
```suggestion
    "Der resultierende, an die oberste Ebene übergebene Wert kennzeichnet den, hinsichtlich der Evaluierungsfunktion und Suchtiefe, bestmöglichen Zug."
```

2022-06-03 13:51 UTC, antonplagemann commented
@piuswalter Es sieht so aus als hast du das Bild vom Internet aus eingebunden? Das sollten wir glaube ich nicht machen. Nachher lädt das nicht, die URL gibts nicht mehr oder Hr. Stroetmann ist offline beim ansehen. Und vermutlich steht es auch irgendwo in den Leitlinien das es nicht erlaubt ist 😊 Magst du das noch ändern?

2022-06-05 15:37 UTC, antonplagemann commented
@piuswalter @p-fruck 
Habe die Definition des Suchbaumes mal nach eigenem Empfinden überarbeitet. Wenn das für dich passt kannst du es dann gerne mergen Pius 😊 

![grafik](https://user-images.githubusercontent.com/54081139/172058420-4ba91716-ce7d-4ee3-802d-38396c739ad8.png)

2022-06-05 15:37 UTC, antonplagemann approved these changes

2022-06-05 18:05 UTC, p-fruck approved these changes

2022-06-05 19:47 UTC, merged