Added description for save game function
piuswalter/Chess-AI pull request #70
Opened 2022-06-03 14:45 UTC by piuswalter

2022-06-03 17:42 UTC, p-fruck requested changes

2022-06-03 17:42 UTC, p-fruck commented on src/Main.ipynb
> +    "Die folgenden Funktionen speichert eine gegebene Partie (repräsentiert durch ein gespieltes Board) auf der Festplatte ab. Hierbei werden sämtliche Züge, die Spielernamen und einige weitere Metri
```suggestion
    "Die folgende Funktion speichert eine gegebene Partie (repräsentiert durch ein gespieltes Board) auf der Festplatte ab. Hierbei werden sämtliche Züge, die Spielernamen und einige weitere Metriken gespeichert.\n",
```

2022-06-05 07:27 UTC, antonplagemann approved these changes
👍

2022-06-05 07:38 UTC, p-fruck approved these changes

2022-06-05 07:39 UTC, merged